name: Validate Manifest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r https://raw.githubusercontent.com/flipperdevices/flipper-application-catalog/main/tools/requirements.txt

      - name: Install UFBT SDK
        run: |
          export UFBT_HOME=`realpath venv/ufbt`
          $UFBT_HOME/ufbt update

      - name: Download bundle.py
        run: |
          curl -o bundle.py https://raw.githubusercontent.com/flipperdevices/flipper-application-catalog/main/tools/bundle.py

      - name: Run manifest validation
        run: |
          source venv/bin/activate
          python3 bundle.py --nolint manifest.yml bundle.zip

      - name: Clean up
        run: |
          rm -rf venv bundle.py bundle.zip
